title: Artem Saveliev
logo: logo.svg # You can add own logo.
description: Zolan is modern minimal theme for Jekyll

author:
  name: Artem Saveliev
  image: 01.jpg
  say-hello: Hello, I’m <strong>Artem Saveliev</strong>
  bio: Designs, talks, and writes about <strong>web</strong>, <strong>ethics</strong>, <strong>privacy</strong>, and dev. I share design tutorials, free resources and inspiration. Loves <a href="#">music</a> & riding his bicycle.
